{% set name = "func-adl" %}
{% set version = "3.4.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/func_adl-{{ version }}.tar.gz
  sha256: b0d0b11f70037ef11188d533b6d58d681970532556af12b76cee8090de567ebb

build:
  noarch: python
  # FIXME: https://github.com/iris-hep/func_adl/blob/b67b122de5000e6b3a2541d3ae9770faa7cb6086/setup.py#L55
  script: func_adl_version="{{ version }}" {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }},<3.13
    - make-it-sync

test:
  imports:
    - func_adl
  commands:
    - pip check
    - pip list
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/iris-hep/func_adl
  summary: Functional Analysis Description Language Base Package
  license: MIT
  license_file: LICENSE
  doc_url: https://gordonwatts.github.io/xaod_usage
  dev_url: https://github.com/iris-hep/func_adl

extra:
  recipe-maintainers:
    - gordonwatts
    - matthewfeickert
